WebPeliculas/src/java/com/empresa/proyecto/bean/ImagenesSerieBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.empresa.proyecto.bean;

import com.empresa.proyecto.dao.SerieInterface;
import com.empresa.proyecto.impl.SerieDaoImpl;
import com.empresa.proyecto.model.Serie;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.faces.event.PhaseId;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

/**
 *
 * @author yio
 */
@ManagedBean
@ApplicationScoped
public class ImagenesSerieBean {
    
    public StreamedContent getImagenserie() throws IOException {
        FacesContext context = FacesContext.getCurrentInstance();

        if (context.getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
            // So, we're rendering the HTML. Return a stub StreamedContent so that it will generate right URL.
            return new DefaultStreamedContent();
        }
        else {
            // So, browser is requesting the image. Return a real StreamedContent with the image bytes.
            String idpelis = context.getExternalContext().getRequestParameterMap().get("idpelis");
            SerieInterface si = new SerieDaoImpl();
            
            Serie serie = si.getSerie(Integer.valueOf(idpelis));
            return new DefaultStreamedContent(new ByteArrayInputStream(serie.getImagen()));
        }
    }
    
}

WebPeliculas/web/vista/Bienvenido.xhtml
 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <f:view contentType="text/html">
        <h:head>
            <f:facet name="first">
                <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
                <title>Peliculas.net</title>
            </f:facet>

            <h:outputStylesheet library="css" name="estilos.css"/><!--obteniendo los estilos-->
            <!--llama a los estilos-->
        </h:head>

        <h:body>

            <p:layout fullPage="true">

                <p:layoutUnit position="north" size="100" resizable="false" closable="false" collapsible="false">
                    <f:facet name="header">
                        <p:outputPanel id="buscadorPelicula" >
                            <h:outputText id="globalFilter" style="width:150px" value="-*Bienvenidos*-"  />
                            <!--p:inputText onkeyup="PF('carsTable').filter()" 
                                          placeholder="buscar "/-->
                        </p:outputPanel>
                    </f:facet>
                </p:layoutUnit>

                <p:layoutUnit position="south" size="180" closable="true"  collapsible="true">
                    <p:fieldset legend="Proximamente"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <p:graphicImage  value="../resources/img/joker.jpg" width="100" height="150" /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        <p:graphicImage value="../resources/img/proyectogeminis.jpg" width="100" height="150" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                       <p:graphicImage value="../resources/img/frozen.jpg" width="100" height="150" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                       <p:graphicImage value="../resources/img/21bridges.jpg" width="100" height="150" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <p:graphicImage value="../resources/img/amigoabomi.jpg" width="100" height="150" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                    </p:fieldset>
                </p:layoutUnit>

                <p:layoutUnit position="west" size="200" header="Ocultar" collapsible="true">
                    <p:menu>
                        <p:submenu label="Menu">
                            <p:menuitem value="Peliculas" outcome="/vista/pelicula/peliculas" />
                            <p:menuitem value="Series" outcome="/vista/serie/series" /> 
                        </p:submenu>

                    </p:menu>
                </p:layoutUnit>

                <p:layoutUnit position="center">
                    
                    <p:carousel numVisible="1" effect="easeInStrong" value="#{peliculaBean.listap}" 
                                var="listp" headerText="Peliculas" style="margin-bottom:0; width: 900px; ">
                        <p:tab> 
                            <h:panelGrid columns="2" cellpadding="10" style="background:#BAA227">
                                 <h:outputText  value="#{listp.nombre} " /> <br /> 
                                <p:graphicImage cache="false" id="imgp"  value="#{imagenesBean.image}" width="200" height="320">
                                    <f:param name="idpeli" value="#{listp.idPelicula}"/>
                                </p:graphicImage> 
                                <!--p:graphicImage value="../resources/img/seanillos.jpg" width="150" height="220" /-->
                                <h:outputText value="#{listp.informacion}" />
                            </h:panelGrid>
                        </p:tab>
                         
                    </p:carousel>
                    <p:carousel numVisible="1" effect="easeInStrong" value="#{serieBean.listas}" var="lists"
                                headerText="Series" style="margin-bottom:0; width:900px;">
                        <p:tab>
                            <h:panelGrid columns="2" cellpadding="10" style=" background:#3BA2EB;">
                                 <h:outputText  value="#{lists.nombre} " /> <br /> 
                                <p:graphicImage cache="false" id="imgs"  value="#{imagenesSerieBean.imagenserie}" width="150" height="220">
                                    <f:param name="idpelis" value="#{lists.idSerie}"/>
                                </p:graphicImage> 
                                <!--p:graphicImage value="../resources/img/casapapel.jpg" width="150" height="220" /-->
                                <h:outputText value="#{lists.informacion}" />
                            </h:panelGrid>
                        </p:tab>
                         
                    </p:carousel>
                    <p:fieldset legend="Peliculas Mas vistas"  style="margin-bottom:20px;">
                        <p:carousel numVisible="1" effect="easeInStrong"  value="#{peliculaBean.lstpelVistas}" var="listp" 
                                    style="margin-bottom:0; width: 900px;">
                        <p:tab>
                            <h:panelGrid columns="2" cellpadding="10" style="  background: green;">
                                <h:outputText  value="#{listp.nombre} " /> <br /> 
                                
                                <p:graphicImage cache="false" id="imgp"  value="#{imagenesBean.image}" width="150" height="220">
                                    <f:param name="idpeli" value="#{listp.idPelicula}"/>
                                </p:graphicImage> 
                                  
                                <!--p:graphicImage value="../resources/img/24.jpg" width="150" height="220" /-->
                                   
                                <h:outputText value="#{listp.informacion}" /> <br /> 
                                <h:outputText style="color:yellow;" value="#{listp.calificacion}☆" />
                              </h:panelGrid> 
                        </p:tab>  
                        </p:carousel>
                    </p:fieldset>  
                    
                    <p:fieldset legend="Peliculas Mejor Valoradas"  style="margin-bottom:20px;">
                        <h:panelGrid  columns="2" cellpadding="10" style="width: 900px;  background: #7F0BB9;">
                            
                            <p:galleria value="#{peliculaBean.lstpelMasValoradas}" var="mv" 
                                        panelWidth="500" panelHeight="413" showCaption="true">
                                
                                 <p:graphicImage cache="false" id="imgp"  value="#{imagenesBean.image}"
                                                 alt="Resumen: #{mv.informacion}" title="#{mv.nombre}"
                                                 width="500" height="413">
                                    <f:param name="idpeli" value="#{mv.idPelicula}"/>
                                </p:graphicImage>
                            </p:galleria> 
                        </h:panelGrid>
                    </p:fieldset>
                </p:layoutUnit> 
            </p:layout> 
        </h:body> 
    </f:view>
</html>